---
abstract: 'Dist::Zilla configuration the way DAGOLDEN does it'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::Exception: 0.29
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 3.101460, CPAN::Meta::Converter version 2.101460'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-DAGOLDEN
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Dist::Zilla::PluginBundle::DAGOLDEN:
    file: lib/Dist/Zilla/PluginBundle/DAGOLDEN.pm
    version: 0.007
requires:
  Dist::Zilla: 3.101450
  Dist::Zilla::Plugin::BumpVersionFromGit: 0
  Dist::Zilla::Plugin::CheckChangesHasContent: 0
  Dist::Zilla::Plugin::CheckExtraTests: 0
  Dist::Zilla::Plugin::CompileTests: 0
  Dist::Zilla::Plugin::MetaNoIndex: 0
  Dist::Zilla::Plugin::MetaProvides::Package: 0
  Dist::Zilla::Plugin::MinimumPerl: 0
  Dist::Zilla::Plugin::PodSpellingTests: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::PortabilityTests: 0
  Dist::Zilla::Plugin::Prepender: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0
  Dist::Zilla::Plugin::Repository: 0.13
  Dist::Zilla::Plugin::TaskWeaver: 0
  Dist::Zilla::PluginBundle::Filter: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0.99
  Moose::Autobox: 0
  autodie: 2.00
  namespace::autoclean: 0.09
  perl: 5.006
resources:
  repository: http://github.com/dagolden/dist-zilla-pluginbundle-dagolden
version: 0.007
