use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006000
eval "use Test::Spelling 0.12; use Pod::Wordlist::hanekomu; 1" or die $@;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
BooK
Bruhat
ConfigSlicer
DAGOLDEN
DAGOLDEN's
GatherDir
PluginBundle
PluginRemover
PodCoverage
Walde
attr
ini
David
Golden
dagolden
Christian
walde
Eric
Johnson
eric
Karen
Etheridge
ether
Philippe
book
lib
Dist
Zilla
Pod
Weaver
